version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nottie-db
    restart: always
    environment:
      POSTGRES_DB: nottie_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
