CREATE TABLE comment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT,
    post_id        BIGINT,
    type           VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    workstation_id BIGINT,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE post
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content        VARCHAR(255),
    workstation_id BIGINT,
    creator_id     BIGINT,
    note_id        BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE post_comment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content        VARCHAR(255),
    creator_id     BIGINT,
    post_id        BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    workstation_id BIGINT,
    CONSTRAINT pk_post_comment PRIMARY KEY (id)
);

ALTER TABLE note_collaborator
    ADD CONSTRAINT pk_note_collaborator PRIMARY KEY (note_id, user_id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_WORKSTATION FOREIGN KEY (workstation_id) REFERENCES workstation (id);

ALTER TABLE post_comment
    ADD CONSTRAINT FK_POST_COMMENT_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);

ALTER TABLE post_comment
    ADD CONSTRAINT FK_POST_COMMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE post_comment
    ADD CONSTRAINT FK_POST_COMMENT_ON_WORKSTATION FOREIGN KEY (workstation_id) REFERENCES workstation (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_NOTE FOREIGN KEY (note_id) REFERENCES note (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_WORKSTATION FOREIGN KEY (workstation_id) REFERENCES workstation (id);