ALTER TABLE comment
    DROP CONSTRAINT fk_comment_on_post;

ALTER TABLE comment
    DROP CONSTRAINT fk_comment_on_user;

ALTER TABLE comment
    DROP CONSTRAINT fk_comment_on_workstation;

CREATE TABLE post_interaction
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT,
    post_id        BIGINT,
    type           VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    workstation_id BIGINT,
    CONSTRAINT pk_post_interaction PRIMARY KEY (id)
);

ALTER TABLE post_interaction
    ADD CONSTRAINT FK_POST_INTERACTION_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE post_interaction
    ADD CONSTRAINT FK_POST_INTERACTION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE post_interaction
    ADD CONSTRAINT FK_POST_INTERACTION_ON_WORKSTATION FOREIGN KEY (workstation_id) REFERENCES workstation (id);

DROP TABLE comment CASCADE;