CREATE TABLE task
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    description    VARCHAR(255),
    start_date     TIMESTAMP WITHOUT TIME ZONE,
    end_date       TIMESTAMP WITHOUT TIME ZONE,
    status         VARCHAR(255),
    creator_id     BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    tasks_group_id BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

CREATE TABLE task_category_value
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_id        BIGINT,
    category_id    BIGINT,
    text_value     VARCHAR(255),
    checkbox_value BOOLEAN,
    hex_color      VARCHAR(255),
    CONSTRAINT pk_task_category_value PRIMARY KEY (id)
);

CREATE TABLE task_member
(
    task_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_task_member PRIMARY KEY (task_id, user_id)
);

CREATE TABLE tasks_group
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    workstation_id BIGINT,
    user_id        BIGINT,
    CONSTRAINT pk_tasks_group PRIMARY KEY (id)
);

CREATE TABLE tasks_group_category
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    type           VARCHAR(255),
    tasks_group_id BIGINT,
    CONSTRAINT pk_tasks_group_category PRIMARY KEY (id)
);

ALTER TABLE tasks_group_category
    ADD CONSTRAINT FK_TASKS_GROUP_CATEGORY_ON_TASKS_GROUP FOREIGN KEY (tasks_group_id) REFERENCES tasks_group (id);

ALTER TABLE tasks_group
    ADD CONSTRAINT FK_TASKS_GROUP_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE tasks_group
    ADD CONSTRAINT FK_TASKS_GROUP_ON_WORKSTATION FOREIGN KEY (workstation_id) REFERENCES workstation (id);

ALTER TABLE task_category_value
    ADD CONSTRAINT FK_TASK_CATEGORY_VALUE_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES tasks_group_category (id);

ALTER TABLE task_category_value
    ADD CONSTRAINT FK_TASK_CATEGORY_VALUE_ON_TASK FOREIGN KEY (task_id) REFERENCES task (id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_TASKSGROUP FOREIGN KEY (tasks_group_id) REFERENCES tasks_group (id);

ALTER TABLE task_member
    ADD CONSTRAINT fk_tasmem_on_task FOREIGN KEY (task_id) REFERENCES task (id);

ALTER TABLE task_member
    ADD CONSTRAINT fk_tasmem_on_user FOREIGN KEY (user_id) REFERENCES users (id);