CREATE TABLE user_details
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    enabled BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_user_details PRIMARY KEY (id)
);

CREATE TABLE user_follow
(
    user_followed_id BIGINT NOT NULL,
    user_id          BIGINT NOT NULL
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    profile_img VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE verification_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id     BIGINT,
    expired     BOOLEAN                                 NOT NULL,
    verified    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_verification_token PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE verification_token
    ADD CONSTRAINT uc_verification_token_token UNIQUE (token);

ALTER TABLE user_details
    ADD CONSTRAINT FK_USER_DETAILS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE verification_token
    ADD CONSTRAINT FK_VERIFICATION_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_follow
    ADD CONSTRAINT fk_usefol_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_follow
    ADD CONSTRAINT fk_usefol_on_user_followed FOREIGN KEY (user_followed_id) REFERENCES users (id);