CREATE TABLE workstation
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    profile_img VARCHAR(255)                            NOT NULL,
    creator_id  BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_workstation PRIMARY KEY (id)
);

CREATE TABLE workstation_follows_user
(
    user_followed_id BIGINT NOT NULL,
    workstation_id   BIGINT NOT NULL,
    CONSTRAINT pk_workstation_follows_user PRIMARY KEY (user_followed_id, workstation_id)
);

CREATE TABLE workstation_follows_workstation
(
    workstation_followed_id BIGINT NOT NULL,
    workstation_id          BIGINT NOT NULL,
    CONSTRAINT pk_workstation_follows_workstation PRIMARY KEY (workstation_followed_id, workstation_id)
);

CREATE TABLE workstation_leader
(
    user_id        BIGINT NOT NULL,
    workstation_id BIGINT NOT NULL,
    CONSTRAINT pk_workstation_leader PRIMARY KEY (user_id, workstation_id)
);

CREATE TABLE workstation_member
(
    user_id        BIGINT NOT NULL,
    workstation_id BIGINT NOT NULL,
    CONSTRAINT pk_workstation_member PRIMARY KEY (user_id, workstation_id)
);

ALTER TABLE workstation
    ADD CONSTRAINT FK_WORKSTATION_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);

ALTER TABLE workstation_follows_user
    ADD CONSTRAINT fk_worfoluse_on_user FOREIGN KEY (user_followed_id) REFERENCES users (id);

ALTER TABLE workstation_follows_user
    ADD CONSTRAINT fk_worfoluse_on_workstation FOREIGN KEY (workstation_id) REFERENCES workstation (id);

ALTER TABLE workstation_follows_workstation
    ADD CONSTRAINT fk_worfolwor_on_workstation FOREIGN KEY (workstation_id) REFERENCES workstation (id);

ALTER TABLE workstation_follows_workstation
    ADD CONSTRAINT fk_worfolwor_on_workstation_followed FOREIGN KEY (workstation_followed_id) REFERENCES workstation (id);

ALTER TABLE workstation_leader
    ADD CONSTRAINT fk_worlea_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE workstation_leader
    ADD CONSTRAINT fk_worlea_on_workstation FOREIGN KEY (workstation_id) REFERENCES workstation (id);

ALTER TABLE workstation_member
    ADD CONSTRAINT fk_wormem_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE workstation_member
    ADD CONSTRAINT fk_wormem_on_workstation FOREIGN KEY (workstation_id) REFERENCES workstation (id);