CREATE TABLE note
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255),
    content    TEXT,
    creator_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_note PRIMARY KEY (id)
);

CREATE TABLE note_category_value
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note_id        BIGINT,
    category_id    BIGINT,
    text_value     VARCHAR(255),
    checkbox_value BOOLEAN,
    hex_color      VARCHAR(255),
    CONSTRAINT pk_note_category_value PRIMARY KEY (id)
);

CREATE TABLE note_collaborator
(
    note_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE notes_group
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255),
    CONSTRAINT pk_notes_group PRIMARY KEY (id)
);

CREATE TABLE notes_group_category
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    type           VARCHAR(255),
    notes_group_id BIGINT,
    CONSTRAINT pk_notes_group_category PRIMARY KEY (id)
);

ALTER TABLE notes_group_category
    ADD CONSTRAINT FK_NOTES_GROUP_CATEGORY_ON_NOTES_GROUP FOREIGN KEY (notes_group_id) REFERENCES notes_group (id);

ALTER TABLE note_category_value
    ADD CONSTRAINT FK_NOTE_CATEGORY_VALUE_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES notes_group_category (id);

ALTER TABLE note_category_value
    ADD CONSTRAINT FK_NOTE_CATEGORY_VALUE_ON_NOTE FOREIGN KEY (note_id) REFERENCES note (id);

ALTER TABLE note
    ADD CONSTRAINT FK_NOTE_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);

ALTER TABLE note_collaborator
    ADD CONSTRAINT fk_notcol_on_note FOREIGN KEY (note_id) REFERENCES note (id);

ALTER TABLE note_collaborator
    ADD CONSTRAINT fk_notcol_on_user FOREIGN KEY (user_id) REFERENCES users (id);